### ISSUE TITLE
No information on the README about the future of this package

### ISSUE THREAD

**Issue by etc0de** [pypa/pep517#18]
This package looks very interesting, and I'd love to make use of it in a real non-testing project.

However, it is quite unclear if after the testing period 1. this will vanish entirely, 2. be available with the same name on pypi, 3. be available with a different name/part of something else on pypi, ...

Can you add some information to the README clarifying where this project is heading, and how much sense it makes to use this for more than just playing around at this stage?

**Comment by pfmoore** [comment]
It *is* on PyPI, and will remain so. It's also used by pip for its PEP 517 implementation, so it's not going away. However, your point about documentation is fair.

The project doesn't really have a full-time maintainer at the moment. @takluyver provided the initial implementation, and I contributed a number of fixes in the process of using it in pip. But neither of us want to take on too much commitment to ongoing management of this project. So one of the key things for sustainability will be to get a good community around the project. That means basically interested people using the code and contributing PRs and enhancements.

To be specific, the code in [wrappers.py](https://github.com/pypa/pep517/blob/master/pep517/wrappers.py) and the code supporting that is critical to pip, so that *will* be well-supported (pip will provide plenty of real-world use of that code!). But the other code (in particular `envbuild.py`) is not yet used in real-world code, and pip's implementation (which was developed independently) has hit a number of corner cases that likely haven't been considered in the code here. So in order for `envbuild.py` to be production-ready, it will need some work (probably the best approach would be for someone to look at merging this code and pip's implementation of isolated environments, with the intention of pip using the code here, rather than having its own copy. Don't expect me to do that work, though - I doubt I'll have sufficient free time in the near future.

Hopefully, that gives a fair summary of the current state of the project. I don't know how much of that should go in the docs (some of it is too transitory) but I'll see what I can do.

**Comment by takluyver** [comment]
To give a brief update: the `wrappers` level of functionality is sticking around. The layer above that (`envbuild`, `build`, `check` and `meta`) is gradually going to be deprecated and eventually removed (#91). The [PyPA build project](https://github.com/pypa/build) will contain some of this higher-level functionality for setting up an isolated build environment, installing dependencies, and using it to build a package.

**Comment by takluyver** [comment]
I've clarified this in the README.
