### ISSUE TITLE
Not obvious if `get_requires_for_build_wheel` will modify installed packages state, or how - and other questions

### ISSUE THREAD

**Issue by JonasT** [pypa/pep517#19]
I am very interested in the following code, since it is what I want to use in my project:
```
import os
from pep517.wrappers import Pep517HookCaller

src = 'path/to/source'  # Folder containing 'pyproject.toml'
hooks = Pep517HookCaller(src)
print(hooks.build_sys_requires)  # List of static requirements

config_options = {}   # Optional parameters for backend
# List of dynamic requirements:
print(hooks.get_requires_for_build_wheel(config_options))
```
However, I have a couple of questions, which I suggest should be possibly answered in the README:

1. What happens when the package doesn't provide the new functionality to get this metadata *without* building the wheel? If it builds the wheel in that case, can I possibly configure it to error out instead?
2. Can I somehow prevent any sort of state modification outside of the package dir (installed site packages) by this command? Will it do such modifications ever at all, e.g. when building the wheel as fallback or in other situations. e.g. to satisfy `setup_requires`?
3. If the package examined with this command is already installed in the site-packages, will this in any way interfere with obtaining the information from it in the exact version as found at the `src` path?

**Comment by pfmoore** [comment]
Contribution to the docs gratefully accepted ;-)

If the backend doesn't supply `get_requires_for_build_wheel`, then the wrapper returns `[]`. See https://github.com/pypa/pep517/blob/master/pep517/_in_process.py#L40

What `get_requires_for_build_wheel` does is *entirely* handled by the backend. PEP 517 says nothing on the matter, so a generic wrapper like this can't do anything. There's a `config_options` argument, but they are totally backend-defined. So (a) you'd have to consult the backend docs, and (b) relying on config options will make your code backend specific.

At the moment, there's essentially no real-world experience with what backends can or should do - there are too few alternative backends to draw any real conclusions. Questions like you're asking are likely to need input from backend authors, and may need documenting in PEP 517. But they aren't going to be something that's covered by this project - which will always be based on what the PEP says.

**Comment by JonasT** [comment]
With backend you're referring to e.g. setuptools/distutils I assume?

**Comment by pfmoore** [comment]
Whichever one is specified in `pyproject.toml`.

**Comment by JonasT** [comment]
Sorry, I realize this might be the wrong place for this feedback. Where is the best place for that, the python packaging bugtracker?

**Comment by pfmoore** [comment]
Well, as far as I'm concerned, this (at least `wrappers.py`) is a library to handle all of the bookkeeping needed to call PEP 517 hooks as specified by the PEP. So if you don't use this code, you'll have to write it yourself. If you want isolated build environments, the `envbuild.py` code is basically doing what you'd otherwise have to implement yourself - although there's a proviso in that case, that the code hasn't been used in production, so it may have bugs (but even so, why not contribute fixes here rather than write your own version from scratch?)

It sounds like you don't want to call PEP 517 hooks, but want something else. So it's quite possible this library isn't for you.

However, I will say:

> each setup.py provider is required to implement --install_requires and --setup_requires to print out the according information, and this function has to not modify the site-packages

I'm not sure how you intend to enforce that. You'd need it in a PEP if you are going to rely on it. And furthermore, it's unlikely that any backend other than setuptools will even *use* a file called `setup.py`, so your interface won't make sense for a general backend.

> Am I missing something? Why is this all so horribly complicated? Am I wrong thinking that everyone involved should meet up and figure out a better solution than the current mess?

To be blunt, we *did* that, spending months thrashing out the details of PEP 517. Calling the specification a "mess" is rather dismissive of all the work that went into producing it. Maybe we missed whatever your use case is, but that's likely only because no-one participating in the discussions (which were open to the public, on distutils-sig) mentioned it.

**Comment by pfmoore** [comment]
> Sorry, I realize this might be the wrong place for this feedback. Where is the best place for that, the python packaging bugtracker?

Honestly, I don't know. I don't actually understand what you're trying to do. On the one hand you seem to want a generic way of getting package information, but on the other hand, you are talking about `setup.py`, as if you're only interested in setuptools.

If you are only interested in working with setuptools, then you should probably bring your requirements up on the setuptools tracker. If you want to work with general backends, then the packaging tracker might be better - but you should be prepared to explain what you're trying to do in terms that *don't* assume setuptools is involved. That's *hard*, because there aren't many good examples of alternative backends. I'd recommend looking at flit as an example, but it doesn't handle anything other than pure Python code, so it may be of limited help.

**Comment by JonasT** [comment]
Sorry for calling it a mess, I am pretty clueless I have to admit (e.g. I wasn't aware there are other install methods in real world use not using `setup.py`). So I'm mostly talking of that because I have no idea what I'm talking about :grimacing: 

For completeness sake, my use case is just to get the dependencies without installing (because I'm in a cross compile environment, so installing at that stage doesn't make any sense) or touching anything, and to query them for longer deps-of-deps chains (so a throaway virtualenv for each query could become a perf issue).

Thanks for all your responses, I hope I didn't thrash too much on things. As written above I am just surprised at how complicated a simple "list the package dependencies" can get, but I shouldn't be judging given I have no clue about the python packaging ecosystem as a whole. Sorry about that

**Comment by JonasT** [comment]
> If you are only interested in working with setuptools, then you should probably bring your requirements up on the setuptools tracker

Forgot to answer that part: I did, and they said they weren't interested, in part because they want to get such setuptools-specific logic out and into generic tools instead (like this one)

**Comment by pfmoore** [comment]
:-)

I think that your biggest problem is that getting dependencies without installing is perfectly possible. But what's *not* possible is getting dependencies without *building*. The problem is that `setup.py` is executable code, and can to anything at all in the process of doing a build. We'd all like things to be more static, but backward compatibility prevents us from making assumptions - so we're left in a situation where of necessity, general tools have to be prepared to run arbitrary code, and execute arbitrary build steps, to work out how to install a Python package.

Most real-world situations are far easier than that, and 99.9% of the capability of setuptools is mostly unused. But generic tools have to cope with the worst case.

I don't have a good answer for you. You may be able to make simplifying assumptions that mean you can handle the problem relatively simply. But I don't know your requirements well enough to suggest how - and from what you say, I suspect you don't have the background in packaging to know how either. Sorry there's no better answer for you here...

**Comment by takluyver** [comment]
As an example of the kind of complexity there is, one of the goals in PEP 517 was to allow the build process to determine extra requirements - e.g. extension modules which build on numpy might need to be installed with the same version of numpy they were built against.

As @pfmoore says, it really depends how general you need to make it. For lots of popular packages, it's probably sufficient to download a wheel from PyPI and extract requirements from its metadata - this can be done without installing anything or running any unknown code. But the closer you want to get to 100% coverage, the more complexity you'll need. It's a classic 80/20 situation - you can get 80% of the result with 20% of the effort (or even less...)

**Comment by JonasT** [comment]
Thanks for the very extensive responses, this was all extremely helpful! :heart: I forgot to close this so I will do so now
