### ISSUE TITLE
hooks.get_requires_for_build_wheel may return pep 508 url, but BuildEnvironment.pip_install() cannot process that

### ISSUE THREAD

**Issue by etc0de** [pypa/pep517#43]
The `hooks.get_requires_for_build_wheel` function may return a pep 508 url if that is used in `install_requires()` (which works completely fine outside of `pep517` usage, I can install this package just fine), but BuildEnvironment.pip_install() cannot process that. However, this is exactly how `envbuild.py` uses things:

```
...
with BuildEnvironment() as env:
        env.pip_install(requires)
        reqs = hooks.get_requires_for_build_wheel(config_settings)
        env.pip_install(reqs)
```
And this will lead to the following error:
```
Requirement 'e @ https://github.com/e/e/archive/master.zip' looks like a filename, but the file does not exist
Processing ./e @ https:/github.com/e/e/archive/master.zip
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/e/Develop/python-for-android/e @ https:/github.com/e/e/archive/master.zip'
```
So it looks to me like either `envbuild.py` or pip are broken here

**Comment by JonasT** [comment]
Could someone give me just a very extremely basic feedback whether this is a pip error, pep517 bug, or something else? Because I run into the same issue outside of `pep517` in my own handling somewhere else and I got a workaround I'm not particularly fond of, so I'm interested in finding out with whom the culprit lies here so I can find out how to properly address this in my own code

**Comment by pfmoore** [comment]
From [here](https://www.python.org/dev/peps/pep-0517/#get-requires-for-build-wheel), "This hook MUST return an additional list of strings containing PEP 508 dependency specifications,"

`wobblui @ https://github.com/JonasT/wobblui/archive/master.zip` is a PEP 508 URL requirement.

However, the [pip manual](https://pip.pypa.io/en/latest/reference/pip_install/#requirement-specifiers) points out that "pip does not support the url_req form of specifier at this time" - things are currently moving fast in this area, so I think it would be best to assume "limited support" for URL specs, at best.

**Comment by JonasT** [comment]
The PEP 508 URL format works in `setup_requires` though (even when installing the package with `pip`), which means this package is perfectly able to be installed including with pip, but the above `pep517` code will always fail.

Isn't this something that should be fixed timely? Surely the buildenv code should be able to handle any package that also installs properly?

**Comment by JonasT** [comment]
In fact, now that I recall why I used it, I think setuptools didn't like the regular URLs pip prefers in its `requirements.txt` as external repository sources and I actually **had** to use PEP 508 URLs to get the dependency install to work without weird extra flags (like `--process-dependency-links`).

So basically now I can choose whether the package actually installs properly with regular pip use, vs whether it works with pep517 and `envbuild.py`. That seems quite unfortunate

**Comment by JonasT** [comment]
@pfmoore any ideas on how to move forward? are packages that use PEP 508 URLs in `setup_requires` *meant* to break in pep517? (even though they install fine outside of it) if not, maybe there could be some coordination with pip guys, I made a ticket over there: https://github.com/pypa/pip/issues/6306

**Comment by pradyunsg** [comment]
@JonasT, @pfmoore is a pip maintainer. :)

**Comment by JonasT** [comment]
@pradyunsg ah neat :smile: just to emphasize this, I'd be happy not to use PEP 508 URLs *at all*, but as described above I found no other way to make my package's deps work, and it *does* work outside of pep517

**Comment by cjerdonek** [comment]
@JonasT I believe this is the main issue on pip's tracker for discussing the overall issue and workarounds: https://github.com/pypa/pip/issues/5898
(@pradyunsg, feel free to correct me if I'm wrong.)

**Comment by pfmoore** [comment]
> @pfmoore any ideas on how to move forward?

Probably someone needs to write a PR addressing pypa/pip#6306. Personally, I don't use either `setup_requires` or URL links, so it won't be me doing that ;-)

Also, I'd point out that pip doesn't use `envbuild` from this project (it has its own environment builder) so this isn't a high priority issue for pip. (In fact, I know of no-one other than you using the `envbuild` module). While it's quite possible that this issue also affects pip's environment builder, we've had no other issues raised about it, so it's likely extremely rare usage.

**Comment by JonasT** [comment]
> @JonasT I believe this is the main issue on pip's tracke

@cjerdonek that's a different issue, that's "PEP 508 URLs don't support versions / are inadequate when they work". My issue is that they actually *don't* even work in some places, e.g. pep517's envbuild or `pip install -r` (which is related)

> While it's quite possible that this issue also affects pip's environment builder, we've had no other issues raised about it

Um well, didn't I just do exactly that? :laughing:  **This DOES definitely break my package.**

**Comment by JonasT** [comment]
Basically I have a package that depends on `wobblui @ https://github.com/wobblui/wobblui/archive/master.zip` *at setup time* (`setup_requires`) - this breaks envbuild. The package itself isn't published yet because I'm still working on it, but that doesn't make the problem any less real

**Comment by JonasT** [comment]
Just to illustrate the ugly code this requires, look at this:

https://github.com/JonasT/python-for-android/blob/14ddf3390e37020683f7ecd7556f42d98e2cfc7e/pythonforandroid/pythonpackage.py#L21

I mean come on, I can't seriously keep that in like that. But what else am I supposed to do?

**Comment by pfmoore** [comment]
@JonasT Sorry, I may have misunderstood your pip issue, which says "any setuptools package that will have them in setup_requires will result in pep517's envbuild.py attempting to install it with pip". I assumed from that, you were referring to this project's `envbuild.py`. Calling this project `pep517` may have been a confusing choice ;-)

Anyway, my point remains. Someone needs to submit a PR.

**Comment by JonasT** [comment]
Yeah I meant this project's `envbuild.py`, I was just being silly and misread your comment :woman_shrugging: never used pip's environment builder

**Comment by JonasT** [comment]
By the way if fixing this in `pip` isn't something that will be prioritized any time soon, then this function:

https://github.com/pypa/pep517/blob/970f48beebf29b0831a3a067da4a0a3daac20193/pep517/envbuild.py#L88

should be changed to have a workaround similar to this:

https://github.com/JonasT/python-for-android/blob/14ddf3390e37020683f7ecd7556f42d98e2cfc7e/pythonforandroid/pythonpackage.py#L21

Because then it would work, and ugly workarounds wouldn't be pushed on downstream code like mine

**Comment by pradyunsg** [comment]
To reiterate/summarize, pypa/pip#5898 is the underlying issue here, and we'd be willing to accept a PR fixing this. :)

**Comment by takluyver** [comment]
I see some hints that something relevant may have been fixed in pip, e.g. https://github.com/pypa/pip/pull/6203

We've come to an agreement that the functionality to create isolated build environments and install build dependencies will live in the [PyPA build project](https://github.com/pypa/build). The `pep517` library will continue to exist as the lower-level piece to work with the interfaces defined by [PEP 517](https://www.python.org/dev/peps/pep-0517/), but the `pep517.envbuild` module and the little command-line interfaces which use it (`pep517.build`, `pep517.check` and `pep517.meta`) will gradually be deprecated and eventually removed as `build` becomes more stable. See #91 for more on that process.

So I'm closing this, as there won't be any further significant work here on `BuildEnvironment`. And it doesn't make sense to fix it at a lower level, because the URL requirement should be valid.
